# Generated by Django 4.2.1 on 2023-05-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_option3_question_option4'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'opt1'), ('2', 'opt2'), ('3', 'opt3'), ('4', 'opt4')], max_length=50, null=True),
        ),
    ]
