# Generated by Django 4.2.1 on 2023-05-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_gender_question_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(blank=True, choices=[('1', 'opt1'), ('2', 'opt2'), ('3', 'opt3'), ('4', 'opt4')], max_length=50, null=True)),
                ('fk_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
    ]
