# Generated by Django 4.2.1 on 2023-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_answer_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
