# Generated by Django 4.2.1 on 2023-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answer_mark_alter_answer_fk_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mark',
            field=models.CharField(max_length=100),
        ),
    ]
